<a href="https://colab.research.google.com/github/zhrhatqh/PDS/blob/main/40_Zahrah_Atiqah_M_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#PANDAS

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd
import numpy as np
df = pd.read_csv(
    '/content/drive/MyDrive/Numpy&Pandas_Zahrah/Dataset Pandas.csv')
df.head()

      nama  jan  feb  mar  apr  Unnamed: 5
0     Andi  100  135   85   75         NaN
1     Budi  200  240  185  160         NaN
2  Chandra  300  315  285  190         NaN
3     Dudi  250  270  230  200         NaN
4      Eko  150  195  110  100         NaN

In [ ]:
#P3
ds1 = pd.Series([2, 4, 6, 8, 10])
ds2 = pd.Series([1, 3, 5, 7, 9])
dsa = ds1 + ds2  #operasi jumlah
dsb = ds1 - ds2
dsc = ds1 * ds2
dsd = ds1 / ds2
print(dsa)
print(dsb)
print(dsc)
print(dsd)
#pandas melakukan operasi berdasarkan index yang sama

0     3
1     7
2    11
3    15
4    19
dtype: int64
0    1
1    1
2    1
3    1
4    1
dtype: int64
0     2
1    12
2    30
3    56
4    90
dtype: int64
0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.111111
dtype: float64

In [ ]:
#P6
#generate angka random
num_state = np.random.RandomState(100)
num_series = pd.Series(num_state.normal(10, 4, 20))
print(num_series)
#print(num_state)

0      3.000938
1     11.370722
2     14.612143
3      8.990256
4     13.925283
5     12.056875
6     10.884719
7      5.719827
8      9.242017
9     11.020006
10     8.167892
11    11.740654
12     7.665620
13    13.267388
14    12.690883
15     9.582355
16     7.874878
17    14.118931
18     8.247458
19     5.526727
dtype: float64

In [ ]:
#P.12.1
df.loc[0]
df.iloc[0]
df[:1]

   nama  jan  feb  mar  apr  Unnamed: 5
0  Andi  100  135   85   75         NaN

In [ ]:
#P12.4
df.loc[:, ['nama', 'apr']]
df.iloc[:, [0, 4]]
df[['nama', 'apr']]

      nama  apr
0     Andi   75
1     Budi  160
2  Chandra  190
3     Dudi  200
4      Eko  100
5    Fahri   45
6     Gina   70
7   Herman   85
8   Indara  270
9     Joni  155

In [ ]:
#P12.5
df.loc[:, 'nama':'feb']
df.iloc[:, :3]
df[['nama', 'jan', 'feb']]

      nama  jan  feb
0     Andi  100  135
1     Budi  200  240
2  Chandra  300  315
3     Dudi  250  270
4      Eko  150  195
5    Fahri   95  130
6     Gina  125  175
7   Herman  130  155
8   Indara  320  374
9     Joni  200  220

In [ ]:
#P12.5
df.loc[:, :]
df.loc[:,]
df.iloc[:, :]

      nama  jan  feb  mar  apr  Unnamed: 5
0     Andi  100  135   85   75         NaN
1     Budi  200  240  185  160         NaN
2  Chandra  300  315  285  190         NaN
3     Dudi  250  270  230  200         NaN
4      Eko  150  195  110  100         NaN
5    Fahri   95  130   75   45         NaN
6     Gina  125  175  110   70         NaN
7   Herman  130  155  100   85         NaN
8   Indara  320  374  300  270         NaN
9     Joni  200  220  175  155         NaN

In [ ]:
#P13.1
#1. sama dengan
df[df['jan'] == 200]
df[df.jan.eq(200)]

   nama  jan  feb  mar  apr  Unnamed: 5
1  Budi  200  240  185  160         NaN
9  Joni  200  220  175  155         NaN

In [ ]:
#P13.1
#2. Memilih Angka tidak sama dengan
df[df['jan'] != 200]
df[df.jan.ne(200)]
df[~(df['jan'] == 200)]

      nama  jan  feb  mar  apr  Unnamed: 5
0     Andi  100  135   85   75         NaN
2  Chandra  300  315  285  190         NaN
3     Dudi  250  270  230  200         NaN
4      Eko  150  195  110  100         NaN
5    Fahri   95  130   75   45         NaN
6     Gina  125  175  110   70         NaN
7   Herman  130  155  100   85         NaN
8   Indara  320  374  300  270         NaN

In [ ]:
#P13.1
#3. Memilih Angka Lebih Dari
df[df['jan'] > 200]
df[df.jan.gt(200)]

      nama  jan  feb  mar  apr  Unnamed: 5
2  Chandra  300  315  285  190         NaN
3     Dudi  250  270  230  200         NaN
8   Indara  320  374  300  270         NaN

In [ ]:
#P13.1
#4. Memilih Lebih Dari atau Sama Dengan
df[df['jan'] >= 200]
df[df.jan.ge(200)]

      nama  jan  feb  mar  apr  Unnamed: 5
1     Budi  200  240  185  160         NaN
2  Chandra  300  315  285  190         NaN
3     Dudi  250  270  230  200         NaN
8   Indara  320  374  300  270         NaN
9     Joni  200  220  175  155         NaN

In [ ]:
#P13.1
#5. Memilih Kurang Dari atau Sama Dengan
df[df['jan'] < 200]
df[df.jan.lt(200)]

     nama  jan  feb  mar  apr  Unnamed: 5
0    Andi  100  135   85   75         NaN
4     Eko  150  195  110  100         NaN
5   Fahri   95  130   75   45         NaN
6    Gina  125  175  110   70         NaN
7  Herman  130  155  100   85         NaN

In [ ]:
#P13.1
# 6. Memilih Kurang Dari atau Sama Dengan
df[df['jan'] <= 200]
df[df.jan.le(200)]

     nama  jan  feb  mar  apr  Unnamed: 5
0    Andi  100  135   85   75         NaN
1    Budi  200  240  185  160         NaN
4     Eko  150  195  110  100         NaN
5   Fahri   95  130   75   45         NaN
6    Gina  125  175  110   70         NaN
7  Herman  130  155  100   85         NaN
9    Joni  200  220  175  155         NaN